begin;

alter table if exists public.repairs
  add column if not exists gross_profit numeric(10, 2) not null default 0;

alter table if exists public.repairs
  add column if not exists item_price numeric(10, 2) not null default 0;

alter table if exists public.repairs
  add column if not exists item_details text;

create table if not exists public.repair_items (
  id           bigint generated by default as identity primary key,
  repair_id    bigint not null references public.repairs(id) on delete cascade,
  inventory_id bigint not null references public.inventory(id) on delete restrict,
  qty          integer not null check (qty > 0),
  unit_cost    numeric(10, 2) not null default 0,
  created_at   timestamptz not null default now()
);

create index if not exists idx_repair_items_repair_id on public.repair_items (repair_id);
create index if not exists idx_repair_items_inventory_id on public.repair_items (inventory_id);

do $$
begin
  if to_regclass('public.sales') is not null then
    insert into public.repair_items (repair_id, inventory_id, qty, unit_cost, created_at)
    select
      s.repair_id,
      s.inventory_id,
      s.qty,
      s.unit_cost,
      s.created_at
    from public.sales s
    where s.repair_id is not null
      and not exists (
        select 1
        from public.repair_items ri
        where ri.repair_id = s.repair_id
          and ri.inventory_id = s.inventory_id
          and ri.qty = s.qty
          and ri.unit_cost = s.unit_cost
          and ri.created_at = s.created_at
      );
  end if;
end $$;

update public.repairs
set gross_profit = coalesce(nullif(gross_profit, 0), fee, 0),
    fee = coalesce(nullif(gross_profit, 0), fee, 0);

with repair_summary as (
  select
    ri.repair_id,
    coalesce(sum(ri.qty * ri.unit_cost), 0) as item_price,
    string_agg(coalesce(i.name, 'Item #' || ri.inventory_id) || ' x' || ri.qty, ', ' order by ri.created_at desc) as item_details
  from public.repair_items ri
  left join public.inventory i on i.id = ri.inventory_id
  group by ri.repair_id
)
update public.repairs r
set item_price = coalesce(rs.item_price, 0),
    item_details = rs.item_details
from repair_summary rs
where rs.repair_id = r.id;

update public.repairs r
set item_price = 0,
    item_details = null
where not exists (
  select 1
  from public.repair_items ri
  where ri.repair_id = r.id
);

drop table if exists public.sales cascade;
drop table if exists public.weekly_snapshots cascade;

drop table if exists public.sales_dev cascade;
drop table if exists public.weekly_snapshots_dev cascade;

commit;
